const RESPONSES = {
  SALUDO: "Hola. Soy el asistente de Cáceres & Casio.\nAntes de hablar de una póliza, ubiquemos qué necesitas decidir.\n¿Qué situación quieres revisar?",
  PRECIO: "Sí, podemos llegar a un número.\nPero primero necesito entender qué estás intentando resolver.\n¿Es para una persona, una empresa, un auto, salud, vida o patrimonio?",
  PRECIO_CONTINUACION: "Comparar precio ayuda solo si estamos viendo lo mismo.\n\n¿Qué estás comparando: costo, cobertura, requisito o exclusiones?",
  PATRIMONIO_PROPIEDAD: "Con inmuebles, no basta con ver el valor del bien.\n\n¿Son propios, rentados o comerciales?",
  PATRIMONIO_PROPIEDAD_CONTINUACION: "Para ordenarlo, dime qué pesa más ahora.\n\n¿Daño al inmueble, inquilinos, responsabilidad o continuidad de renta?",
  PATRIMONIO_AUTO: "En auto, la cobertura depende mucho del uso.\n\n¿Qué uso tiene el vehículo: personal, familiar, trabajo o plataforma?",
  PATRIMONIO_AUTO_CONTINUACION: "Antes de hablar de amplia o limitada, ubiquemos qué te preocupa.\n\n¿Robo, choque, terceros o pérdida total?",
  FLOTILLA: "En flotilla, no basta con contar unidades.\n\n¿Qué mueven y en qué tipo de rutas operan?",
  FLOTILLA_CONTINUACION: "Para ordenar la operación, empecemos por rutas.\n\n¿Son locales, foráneas o mixtas?",
  PATRIMONIO_GENERAL: "Blindar patrimonio no siempre significa comprar más seguros.\n\n¿Qué te preocupa más: demanda, inmuebles, deuda u operación?",
  EMPRESA: "Eso normalmente viene de un contrato o requisito.\n\n¿Te lo pide un cliente, una obra, una plaza o una licitación?",
  EMPRESA_CONTINUACION: "Entonces hay que ubicar qué responsabilidad te están trasladando.\n¿Te piden cubrir daños, operación, terceros o cumplimiento?",
  SALUD: "Ese dato puede influir, pero no conviene detallarlo por aquí.\n\n¿Buscas contratar por primera vez o revisar una póliza actual?",
  SALUD_CONTINUACION: "Para cuidar tu privacidad, no necesito detalles médicos por aquí.\n\n¿La duda es una exclusión, renovación o cambio de póliza?",
  SALUD_ACEPTACION: "No conviene prometer aceptación sin revisar el caso.\nUn padecimiento previo no siempre significa rechazo, pero sí cambia la forma de analizarlo.\n¿Ya tienes una póliza vigente o sería contratación nueva?",
  VIDA: "Cuando alguien depende de tu ingreso, primero hay que medir consecuencia.\n¿Hay dependientes, deuda o empresa de por medio?",
  VIDA_CONTINUACION: "Separémoslo por consecuencia.\n\n¿Te preocupa ingreso, deuda, dependientes o continuidad del negocio?",
  FAMILIA: "Familia puede apuntar a ingreso, salud o patrimonio.\n\n¿Qué te preocupa más: faltar, enfermar, una deuda o una vivienda?",
  FAMILIA_CONTINUACION: "Para no responder en abstracto, ubiquemos la consecuencia principal.\n\n¿Dependen de tu ingreso o la preocupación va por salud o patrimonio?",
  INFORMACION: "Para orientarte bien, primero necesito ubicar la decisión.\n¿Tiene que ver con tu negocio, patrimonio, salud, auto o ingreso?",
  CITA: "Podemos revisarlo en una conversación.\nAntes de agendar, necesito ubicar el tema.\n¿La llamada sería por empresa, salud, vida, auto, patrimonio o contrato?",
  APPOINTMENT_DATA: "Para dejarlo encaminado, necesito dos datos:\ntu nombre y un horario posible.\nPor ejemplo: Franklin, mañana 11:00.",
  APPOINTMENT_NEED_TIME: "Gracias, {name}.\nMe falta el horario para dejarlo claro.\n¿Te funciona mañana en la mañana, en la tarde o propones una hora?",
  APPOINTMENT_NEED_NAME: "De acuerdo.\nTengo el horario: {schedule}.\nSolo necesito tu nombre para registrarlo.",
  APPOINTMENT_NEED_NAME_GENERIC: "De acuerdo.\nSolo necesito tu nombre para registrarlo.\n¿A nombre de quién lo dejamos?",
  APPOINTMENT_NEED_DAY: "Para registrarlo bien, dime el día y si es por la mañana o por la tarde.",
  APPOINTMENT_READY_NEED_TOPIC: "Perfecto, {name}.\nDejo como opción {schedule}.\nAntes de confirmarlo, dime brevemente qué tema quieres revisar en la llamada.",
  APPOINTMENT_READY_WITH_TOPIC: "Perfecto, {name}.\nDejo como opción {schedule}.\nTe contactaremos para confirmar el horario.",
  APPOINTMENT_READY_COMPLETE: "Perfecto, {name}.\nDejo como opción {schedule}.\nTema: {topic}.\nTe contactaremos para confirmar el horario.",
  APPOINTMENT_FLEXIBLE: "Podemos manejarlo sencillo.\nPropón una opción: mañana en la mañana, mañana en la tarde o pasado mañana.",
  APPOINTMENT_DURATION: "La primera conversación suele durar cerca de 20 minutos.\n\n¿Qué tema necesitas revisar?",
  APPOINTMENT_COST: "Antes de hablar de costo, hay que saber qué se va a revisar.\n\n¿Es empresa, salud, vida, auto, patrimonio o contrato?",
  APPOINTMENT_URGENT: "Si es urgente, primero hay que ubicar qué está presionando la decisión.\n¿Viene de un contrato, siniestro, salud, flotilla o patrimonio?",
  APPOINTMENT_TODAY: "Hoy solo conviene priorizar si hay una decisión concreta.\n¿Qué tema necesitas revisar?",
  APPOINTMENT_LINK: "Por ahora lo dejamos registrado por este medio.\nDime tu nombre y horario preferido, y te contactaremos para confirmar.",
  AGRESIVO: "Puedo responder directo, pero necesito contexto.\n¿Quieres revisar un caso concreto o solo buscas precio?",
  AGRESIVO_CONTINUACION: "Puedo continuar si mantenemos la conversación enfocada.\n\n¿Quieres revisar el caso o prefieres dejarlo aquí?",
  INSULTO: "Puedo continuar, pero necesito mantener la conversación con respeto.\n\n¿Qué situación necesitas resolver?",
  INSULTO_CONTINUACION: "Así no puedo hacer una revisión útil.\n\n¿Seguimos con la situación que quieres resolver o lo dejamos aquí?",
  CURIOSO_BAJO: "Podemos orientarlo sin forzar una decisión.\n\n¿Qué quieres entender: patrimonio, negocio, salud, ingreso, auto o contrato?",
  CURIOSO_BAJO_CONTINUACION: "Si solo estás explorando, mantengámoslo simple.\n¿Qué tema te interesa revisar primero?",
  PIRATEO_SISTEMA: "Esa parte no se comparte por este medio.\n\nPuedo ayudarte a revisar una situación concreta.\n¿Qué caso necesitas analizar?",
  PIRATEO_SISTEMA_CONTINUACION: "Esa parte no se comparte por este medio.\n\nPuedo ayudarte a revisar una situación concreta.\n¿Qué caso necesitas analizar?",
  REGION_NORTE: "En esa zona importa mucho el contexto operativo.\n\n¿Qué actividad o bien quieres revisar?",
  REGION_BAJIO: "En esa zona suele pesar el crecimiento y la continuidad.\n\n¿Qué quieres revisar primero?",
  REGION_CENTRO: "En el centro del país cambian mucho movilidad y exposición.\n\n¿Es personal, patrimonial o de empresa?",
  REGION_SURESTE: "En esa zona suelen pesar clima, operación e inmuebles.\n\n¿Qué situación quieres proteger o corregir?",
  ASEGURADORAS: "La marca no debería ser el punto de partida.\nPrimero ubiquemos qué quieres resolver.\n¿Costo, cobertura, requisito o exclusión?",
  COTIZACION_INMEDIATA: "Una cotización sin contexto puede salir mal orientada.\nPrimero dime qué estás intentando resolver.\n¿Es personal, empresa, auto, flotilla o contrato?",
  EVASIVO: "No necesito información delicada, pero sí contexto mínimo.\n\n¿Es personal, negocio, auto, salud o patrimonio?",
  EVASIVO_CONTINUACION: "Sin ese contexto solo habría una respuesta genérica.\nSi no quieres avanzar ahora, podemos dejarlo aquí.",
  SALIDA_ELEGANTE: "No voy a forzar la conversación.\n\nCuando quieras revisar el caso con más claridad, puedes escribir nuevamente.",
  DESCONOCIDO: "Todavía no me queda claro qué riesgo quieres revisar.\n¿Hablamos de una persona, una empresa, un auto, una flotilla o un patrimonio?",
};

const CONTINUATION_BY_INTENT = {
  AGRESIVO: RESPONSES.AGRESIVO_CONTINUACION,
  INSULTO: RESPONSES.INSULTO_CONTINUACION,
  CURIOSO_BAJO: RESPONSES.CURIOSO_BAJO_CONTINUACION,
  PIRATEO_SISTEMA: RESPONSES.PIRATEO_SISTEMA_CONTINUACION,
  EVASIVO: RESPONSES.EVASIVO_CONTINUACION,
  APPOINTMENT_FLEXIBLE: RESPONSES.APPOINTMENT_FLEXIBLE,
  PRECIO: RESPONSES.PRECIO_CONTINUACION,
  PATRIMONIO_PROPIEDAD: RESPONSES.PATRIMONIO_PROPIEDAD_CONTINUACION,
  PATRIMONIO_AUTO: RESPONSES.PATRIMONIO_AUTO_CONTINUACION,
  FLOTILLA: RESPONSES.FLOTILLA_CONTINUACION,
  EMPRESA: RESPONSES.EMPRESA_CONTINUACION,
  SALUD: RESPONSES.SALUD_CONTINUACION,
  VIDA: RESPONSES.VIDA_CONTINUACION,
  FAMILIA: RESPONSES.FAMILIA_CONTINUACION,
  PATRIMONIO_GENERAL: RESPONSES.DESCONOCIDO,
  INFORMACION: RESPONSES.DESCONOCIDO,
  SALUDO: RESPONSES.DESCONOCIDO,
  DESCONOCIDO: RESPONSES.DESCONOCIDO,
};

module.exports = {
  RESPONSES,
  CONTINUATION_BY_INTENT,
};
