const RESPONSES = {
  SALUDO: "Hola. Soy el asistente de Cáceres & Casio.\n\nUna póliza no debería ser el punto de partida.\nPrimero necesitamos entender el riesgo que puede afectar tu decisión.\n\n¿Qué situación quieres revisar?",
  PRECIO: "Tiene sentido querer un número.\nPero si no entendemos el riesgo, el precio puede engañar.\n¿Es para ti, tu empresa, un auto, una flotilla o un contrato?",
  PRECIO_CONTINUACION: "Comparar solo precio puede confundir si no hablamos del mismo riesgo.\n¿Qué estás comparando: costo, cobertura, requisito o exclusiones?",
  PATRIMONIO_PROPIEDAD: "Con inmuebles, el riesgo no está solo en el bien.\nTambién puede estar en terceros, rentas o responsabilidad.\n¿Son propios, rentados o comerciales?",
  PATRIMONIO_PROPIEDAD_CONTINUACION: "Para ubicarlo mejor, dime qué pesa más ahora.\n¿Daño al inmueble, inquilinos, responsabilidad o continuidad de renta?",
  PATRIMONIO_AUTO: "En auto, la cobertura depende mucho del uso.\nNo es lo mismo personal, familiar, trabajo o plataforma.\n¿Qué uso tiene el vehículo?",
  PATRIMONIO_AUTO_CONTINUACION: "Antes de hablar de amplia o limitada, conviene ubicar la exposición.\n¿Qué te preocupa más: robo, choque, terceros o pérdida total?",
  FLOTILLA: "En flotilla, el riesgo no está solo en las unidades.\nTambién está en rutas, carga, choferes, robo y continuidad.\n¿Qué mueven y con qué frecuencia?",
  FLOTILLA_CONTINUACION: "Para revisar transporte, primero ubiquemos la operación.\n¿Son rutas locales, foráneas o mixtas?",
  PATRIMONIO_GENERAL: "Blindar patrimonio no siempre significa comprar más seguros.\n¿Qué te preocupa más: demanda, inmueble, deuda, operación o responsabilidad?",
  EMPRESA: "Antes de pensar en una póliza, hay que ubicar el origen del riesgo.\n¿Viene de contrato, licitación, cliente, autoridad, obra, plaza, arrendador o siniestro?",
  EMPRESA_CONTINUACION: "Si viene de contrato, licitación o siniestro, conviene revisar el origen con cuidado.\n¿Qué responsabilidad te están pidiendo cubrir?",
  SALUD: "Ese dato puede ser relevante, pero no conviene revisarlo de forma superficial por este medio.\n¿Buscas contratar por primera vez, revisar una póliza actual o entender una exclusión?",
  SALUD_CONTINUACION: "Para cuidar tu privacidad, no necesito detalles médicos por aquí.\n¿La duda es aceptación, exclusión, renovación o cambio de póliza?",
  VIDA: "Cuando alguien depende de tu ingreso, la pregunta no empieza en la suma asegurada.\n¿Hay dependientes, deuda o empresa de por medio?",
  VIDA_CONTINUACION: "Para ubicar la decisión, separémoslo por riesgo.\n¿Te preocupa ingreso, deuda, dependientes o continuidad del negocio?",
  FAMILIA: "Familia puede significar ingreso, salud o patrimonio.\n¿Qué te preocupa más: faltar, enfermar, una deuda o una vivienda?",
  FAMILIA_CONTINUACION: "Para no responder en abstracto, ubiquemos la consecuencia principal.\n¿Dependen de tu ingreso o la preocupación va por salud o patrimonio?",
  INFORMACION: "Para ubicarlo mejor, dime qué se parece más a tu caso:\npatrimonio, negocio, salud, ingreso, auto, contrato o póliza existente.",
  CITA: "Podemos avanzar si primero ubicamos el caso.\n¿La revisión sería sobre empresa, salud, vida, auto, patrimonio o contrato?",
  APPOINTMENT_DATA: "Para agendarlo sin vueltas, dime solo dos datos:\ntu nombre y un horario posible.\nPor ejemplo: Franklin, mañana 11:00.",
  APPOINTMENT_NEED_TIME: "Gracias, {name}.\nSolo falta el horario.\n¿Prefieres mañana en la mañana, mañana en la tarde o propones una hora?",
  APPOINTMENT_NEED_NAME: "De acuerdo.\nTengo el horario: {schedule}.\nSolo necesito tu nombre para registrar la revisión.",
  APPOINTMENT_NEED_NAME_GENERIC: "De acuerdo.\nSolo necesito tu nombre para registrar la revisión.\n¿A nombre de quién la dejamos?",
  APPOINTMENT_NEED_DAY: "Para registrarlo bien, dime el día y si es por la mañana o por la tarde.",
  APPOINTMENT_FLEXIBLE: "Podemos manejarlo sencillo.\nPropón una opción: mañana en la mañana, mañana en la tarde o pasado mañana.\nCon eso lo ubicamos.",
  APPOINTMENT_DURATION: "La revisión inicial suele durar cerca de 20 minutos.\nSirve para ubicar el riesgo antes de hablar de opciones.\n¿Qué tema necesitas revisar?",
  APPOINTMENT_COST: "Antes de hablar de costo, hay que saber qué decisión se va a revisar.\n¿Es empresa, salud, vida, auto, patrimonio o contrato?",
  APPOINTMENT_URGENT: "Si es urgente, primero necesito ubicar el motivo.\n¿Es contrato, licitación, siniestro, salud, flotilla o patrimonio?",
  APPOINTMENT_TODAY: "Hoy solo conviene priorizar si hay una decisión concreta.\n¿Qué tema necesitas revisar?",
  APPOINTMENT_LINK: "Por ahora lo dejamos registrado por este medio.\nDime tu nombre y horario preferido, y te contactaremos para confirmar.",
  AGRESIVO: "Voy directo: sin contexto no conviene recomendar.\n¿Quieres revisar un caso concreto o solo buscas precio?",
  AGRESIVO_CONTINUACION: "Puedo continuar si mantenemos la conversación enfocada.\nCáceres & Casio trabaja entendiendo el riesgo, no discutiendo por presión.\n¿Quieres revisar el caso o prefieres dejarlo aquí?",
  INSULTO: "Puedo continuar, pero necesito mantener la conversación con respeto.\nSi quieres revisar un riesgo real, dime qué situación necesitas resolver.",
  INSULTO_CONTINUACION: "Así no puedo hacer una revisión útil.\nSi deseas continuar, enfoquemos la conversación en el riesgo o la decisión que necesitas tomar.",
  CURIOSO_BAJO: "Podemos orientarlo sin forzar una decisión.\n¿Qué quieres entender: patrimonio, negocio, salud, ingreso, auto o contrato?",
  CURIOSO_BAJO_CONTINUACION: "Si solo estás explorando, mantengámoslo simple.\n¿Qué tema te interesa revisar primero?",
  PIRATEO_SISTEMA: "El método interno de Cáceres & Casio no se comparte.\nLo importante aquí es entender tu caso y el riesgo que necesitas revisar.\n¿Tienes una situación concreta que quieras analizar?",
  PIRATEO_SISTEMA_CONTINUACION: "El método interno de Cáceres & Casio no se comparte.\nLo importante aquí es entender tu caso y el riesgo que necesitas revisar.\n¿Tienes una situación concreta que quieras analizar?",
  REGION_NORTE: "En esa zona el contexto operativo importa mucho.\nUso, rutas, exposición y continuidad pueden cambiar la decisión.\n¿Qué actividad o bien quieres revisar?",
  REGION_BAJIO: "En ese contexto suele ser importante revisar crecimiento, operación y continuidad.\nAntes de hablar de una póliza, hay que entender qué puede afectar el negocio o patrimonio.\n¿Qué quieres revisar primero?",
  REGION_CENTRO: "En el centro del país el contexto puede cambiar por movilidad, concentración y exposición.\nConviene ubicar primero dónde está el riesgo real.\n¿Es personal, patrimonial o de empresa?",
  REGION_SURESTE: "En esa zona conviene revisar clima, operación, inmuebles y continuidad.\nNo todo se resuelve con una póliza aislada.\n¿Qué situación quieres proteger o corregir?",
  ASEGURADORAS: "La aseguradora importa, pero después de entender el riesgo.\n¿Qué situación quieres resolver: costo, cobertura, requisito o exclusión?",
  COTIZACION_INMEDIATA: "Una cotización sin contexto puede verse útil, pero puede estar mal orientada.\n¿Es para ti, tu empresa, un auto, una flotilla o un contrato?",
  EVASIVO: "No necesito datos sensibles, pero sí contexto mínimo.\n¿Qué tipo de riesgo es: personal, negocio, auto, salud o patrimonio?",
  EVASIVO_CONTINUACION: "Sin ese contexto solo habría una respuesta genérica.\nSi no quieres avanzar ahora, podemos dejarlo aquí.",
  SALIDA_ELEGANTE: "No voy a forzar la conversación.\n\nSi más adelante quieres revisar el caso con claridad, puedes escribir nuevamente.",
  DESCONOCIDO: "Para ubicarlo mejor, dime qué se parece más a tu caso:\ncomparar costo, cobertura, requisito, exclusión, patrimonio, negocio, salud, ingreso, auto o contrato.",
};

const CONTINUATION_BY_INTENT = {
  AGRESIVO: RESPONSES.AGRESIVO_CONTINUACION,
  INSULTO: RESPONSES.INSULTO_CONTINUACION,
  CURIOSO_BAJO: RESPONSES.CURIOSO_BAJO_CONTINUACION,
  PIRATEO_SISTEMA: RESPONSES.PIRATEO_SISTEMA_CONTINUACION,
  EVASIVO: RESPONSES.EVASIVO_CONTINUACION,
  APPOINTMENT_FLEXIBLE: RESPONSES.APPOINTMENT_FLEXIBLE,
  PRECIO: RESPONSES.PRECIO_CONTINUACION,
  PATRIMONIO_PROPIEDAD: RESPONSES.PATRIMONIO_PROPIEDAD_CONTINUACION,
  PATRIMONIO_AUTO: RESPONSES.PATRIMONIO_AUTO_CONTINUACION,
  FLOTILLA: RESPONSES.FLOTILLA_CONTINUACION,
  EMPRESA: RESPONSES.EMPRESA_CONTINUACION,
  SALUD: RESPONSES.SALUD_CONTINUACION,
  VIDA: RESPONSES.VIDA_CONTINUACION,
  FAMILIA: RESPONSES.FAMILIA_CONTINUACION,
  PATRIMONIO_GENERAL: RESPONSES.DESCONOCIDO,
  INFORMACION: RESPONSES.DESCONOCIDO,
  SALUDO: RESPONSES.DESCONOCIDO,
  DESCONOCIDO: RESPONSES.DESCONOCIDO,
};

module.exports = {
  RESPONSES,
  CONTINUATION_BY_INTENT,
};
